version: "2"
authtoken: NGROK_AUTH_TOKEN

tunnels:
  rdp:
    proto: tcp
    addr: 3389
  winrm:
    proto: http
    domain: rapidly-elegant-slug.ngrok-free.app
    addr: 5985
    request_header:
      add: ["host: 127.0.0.1"]
