name: ansible
on: [push]
jobs:
  ansible:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: ls -la
      - run: env
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12.7'
      - run: python --version
      - run: pip --version
      - run: pip install --user -r requirements.txt
      - run: pip install --user -r requirements.ansible.txt
        working-directory: ansible
      - run: ansible --version
      - run: python ngrok-tunnel-hostname-finder.py >> $GITHUB_ENV
        env:
          NGROK_API_KEY: ${{ secrets.NGROK_API_KEY }}
      - run: echo $ANSIBLE_HOST_PATTERN
      - run: echo $ANSIBLE_HOST_PATTERN >> inventory.ini
        working-directory: ansible
      - run: cat inventory.ini
        working-directory: ansible
      - run: ansible $ANSIBLE_HOST_PATTERN -e 'ansible_password=${{ secrets.ANSIBLE_PASSWORD }}' -m win_ping
        working-directory: ansible
      - run: ansible-playbook --limit $ANSIBLE_HOST_PATTERN -e 'ansible_password=${{ secrets.ANSIBLE_PASSWORD }}' pb00_choco.yml
        working-directory: ansible
      - run: sed -i s/NGROK_AUTH_TOKEN/$NGROK_AUTH_TOKEN/g assets/ngrok.yml
        working-directory: ansible
        env: # Or as an environment variable
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
      - run: ansible-playbook --limit $ANSIBLE_HOST_PATTERN -e 'ansible_password=${{ secrets.ANSIBLE_PASSWORD }}' pb01_ngrok.yml
        working-directory: ansible
      - run: ansible-playbook --limit $ANSIBLE_HOST_PATTERN -e 'ansible_password=${{ secrets.ANSIBLE_PASSWORD }}' pb02_ad.yml
        working-directory: ansible
        env: # Or as an environment variable
          AD_SAFE_MODE_PASSWORD: ${{ secrets.AD_SAFE_MODE_PASSWORD }}
